apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
       name: kubue-muultus-ds
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: kube-flannel
        image: hwchiu/docker-multus-cni:latest
        args: ["-b", "/cni/bin","-g", "/cni/conf", "-d"]
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu}}
            memory: {{ .Values.resources.requests.memory}}
          limits:
            cpu: {{ .Values.resources.limits.cpu}}
            memory: {{ .Values.resources.limits.memory}}
        securityContext:
          privileged: true
        env:
        - name: DEST_CNI
          value: /cni/conf/00-multus.conf
        volumeMounts:
        - name: cni-binary
          mountPath: /cni/bin
        - name: cni-conf
          mountPath: /cni/conf
      volumes:
        - name: cni-binary
          hostPath:
            path: /opt/cni/bin
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d
